### ISSUE TITLE
Usage in `package.json` script throws "const in script mode" error

### ISSUE THREAD

**Issue by mitchhentges** [sindresorhus/cpy-cli#2]
When used in a `package.json` script, the script fails. For example:
```
  "scripts": {
    "bork": "cpy ./node_modules/font-awesome/fonts/* build/fonts/"
  },
```

```
C:\dev\test>npm run bork

> test@0.0.1 bork C:\dev\test
> cpy ./node_modules/font-awesome/fonts/* build/fonts/

C:\dev\test\node_modules\cpy-cli\cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sindresorhus** [comment]
Node.js >=4 required: https://github.com/sindresorhus/cpy-cli/blob/6b7ee085975552554ee6c5d6817f16f505bd88f4/package.json#L23
